name: Build and Deploy

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.9.1"
          rebar3-version: "3"

      - name: Build project
        run: gleam build --target javascript

      - name: Save build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/dev/javascript
          
  package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: [build]
    steps:
      - name: Get build output
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Package to linux executable
        if: matrix.os == 'ubuntu-latest'
        run: bun build --compile --outfile=dhzgit build/dhzgit/dhzgit.mjs --footer="main();"

      - name: Package to macos executable
        if: matrix.os == 'macos-latest'
        run: bun build --compile --outfile=dhzgit.app build/dhzgit/dhzgit.mjs --footer="main();"
      
      - name: Package to windows executable
        if: matrix.os == 'windows-latest'
        run: bun build --compile --outfile=dhzgit.exe build/dhzgit/dhzgit.mjs --footer="main();"

      - name: Save executable
        uses: actions/upload-artifact@v4
        with:
          name: exec-${{ matrix.os }}
          path: dhzgit*
            
  release:
    runs-on: ubuntu-latest
    needs: [package]
    steps:
      - name: Get executables
        uses: actions/download-artifact@v4
        with:
          path: executable
          pattern: exec-*
          merge-multiple: true

      - name: Create a release
        uses: softprops/action-gh-release@v2
        with:
          name: dhzgit ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          prerelease: true
          generate_release_notes: true
          files: |
            executable/*
